pr:
  - master

trigger: none

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      node common/scripts/install-run-rush.js install --bypass-policy
    displayName: rush install

  - script: |
      npm run buildci
    displayName: build ci
